sonar.projectKey=guilherme-teixeira-gomes_oficina-ms-os-service
sonar.organization=guilherme-teixeira-gomes
sonar.sources=src
sonar.tests=tests
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.exclusions=**/node_modules/**,**/dist/**,**/tests/**
