apiVersion: apps/v1
kind: Deployment
metadata:
  name: os-service
  labels:
    app: os-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: os-service
  template:
    metadata:
      labels:
        app: os-service
    spec:
      containers:
      - name: os-service
        image: guitxgomes/oficina-ms-os-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: os-service-config
        - secretRef:
            name: os-service-secret
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "300m"
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 20
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 40
          periodSeconds: 15
