apiVersion: apps/v1
kind: Deployment
metadata:
  name: os-service-postgres
  labels:
    app: os-service-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: os-service-postgres
  template:
    metadata:
      labels:
        app: os-service-postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "postgres"
        - name: POSTGRES_DB
          value: "os_service"
---
apiVersion: v1
kind: Service
metadata:
  name: os-service-postgres
spec:
  selector:
    app: os-service-postgres
  ports:
  - port: 5432
    targetPort: 5432
